G3 29 geneweaver cli client excel parsing tool
TheJacksonLaboratory/geneweaver-client pull request #13
Opened 2023-12-06 18:49 UTC by bergsalex

Adds the convert (or cn) commands to help with parsing excel files. This command takes an excel file as input and converts it to the geneweaver batch upload format.

```
 gweave alpha parse --help
                                                                
 Usage: gweave alpha parse [OPTIONS] COMMAND [ARGS]...          
                                                                
 Tools and utilities to parse data files for use in Geneweaver. 
 The parse commands help to transform data files in various     
 formats into data files that                                   
 can be uploaded to Geneweaver.                                 
                                                                
╭─ Options ────────────────────────────────────────────────────╮
│ --help          Show this message and exit.                  │
╰──────────────────────────────────────────────────────────────╯
╭─ Commands ───────────────────────────────────────────────────╮
│ cn         Alias for `convert` command.                      │
│ convert    Convert files from one format to another.         │
│ utils                                                        │
╰──────────────────────────────────────────────────────────────╯
```

```
gweave alpha parse convert --help
                                                                
 Usage: gweave alpha parse convert [OPTIONS] FILE_PATH          
                                                                
 Convert files from one format to another.                      
                                                                
╭─ Arguments ──────────────────────────────────────────────────╮
│ *    file_path      PATH  [default: None] [required]         │
╰──────────────────────────────────────────────────────────────╯
╭─ Options ────────────────────────────────────────────────────╮
│ *  --value-header        TEXT      [default: None]           │
│                                    [required]                │
│    --to                  [csv|gw]  [default:                 │
│                                    CovertFileType.BATCH]     │
│    --id-header           TEXT      [default: symbol]         │
│    --help                          Show this message and     │
│                                    exit.                     │
╰──────────────────────────────────────────────────────────────╯
```

This PR is being created now for provisional review since it has gotten quite large. I plan to make the following change prior to merging:

1. Add tests for the remaining utils files that were created / coverage back to _at least_ 70%.
2. Changes to the options for the convert command to move the header choices to the prompting steps.

2023-12-06 19:02 UTC, gerring submitted a review, later dismissed
Do there need to be further tests of invalid input files? (xls old versions, xls wrong column layout, xlsx empty file, etc) Checking that the error message is reasonable.

2023-12-07 21:29 UTC, C-1337ka approved these changes

2023-12-07 21:34 UTC, desais-jax approved these changes

2023-12-07 21:35 UTC, merged

2023-12-07 21:35 UTC, gerring requested changes

2023-12-07 21:35 UTC, gerring commented on src/geneweaver/client/cli/alpha/parse/convert.py
> +    """Convert files from one format to another."""
Parameter docs needed? as it's not a _ method and public API

2023-12-07 21:35 UTC, gerring commented on src/geneweaver/client/cli/alpha/parse/utils.py
Is it worth having that if type is xls then raise an exception? I assume that is rooted out already.

2023-12-07 21:35 UTC, gerring commented on src/geneweaver/client/cli/alpha/parse/utils.py
Or just else: raise an exception.

2023-12-07 21:35 UTC, gerring commented on src/geneweaver/client/utils/cli/print/tables.py
> +def print_tabular_data(headers: List[str], rows: List[DictRow]) -> None:
Public method should have parameter type doc.

2023-12-07 21:35 UTC, gerring commented on src/geneweaver/client/utils/cli/prompt/bool.py
> +
parameter type doc?